services:
  elasticsearch:
    container_name: es-vi
    build:
      context: .
      args:
        ES_VERSION: ${ES_VERSION}
    image: elasticsearch-vietnamese
    restart: on-failure
    ports:
      - "9200:9200"
    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx4g -Xms4g"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      xpack.security.enabled: "true"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge